const materials = [
    {
        id:"skill-summary-1",
        image:"./images/Skill_Summary_Volume_1.webp",
    },
    {
        id:"skill-summary-2",
        image:".images/Skill_Summary_Volume_2.webp",
    },
    {
        id:"skill-summary-3",
        image:".images/Skill_Summary_Volume_3.webp",
    },
    {
        id:"damaged-device",
        image:".images/MTL_SL_BOSS2.png",
    },
    {
        id:"diketon",
        image:".images/MTL_SL_KETONE1.png",
    },
    {
        id:"ester",
        image:".images/MTL_SL_RUSH1.png",
    },
    {
        id:"orirock",
        image:".images/MTL_SL_G1.png",
    },
    {
        id:"oriron-shard",
        image:".images/MTL_SL_IRON1.png",
    },
    {
        id:"sugar-substitute",
        image:".images/MTL_SL_STRG1.png",
    },
    {
        id:"device",
        image:".images/MTL_SL_BOSS2.png",
    },
    {
        id:"orirock-cube",
        image:".images/MTL_SL_G2.png",
    },
    {
        id:"oriron",
        image:".images/MTL_SL_IRON2.png",
    },
    {
        id:"polyester",
        image:".images/MTL_SL_RUSH2.png",
    },
    {
        id:"polyketon",
        image:".images/MTL_SL_KETONE2.png",
    },
    {
        id:"sugar",
        image:".images/MTL_SL_STRG1.png",
    },
    {
        id:"aketon",
        image:".images/MTL_SL_KETONE3.png",
    },
    {
        id:"coagulating-gel",
        image:".images/MTL_SL_PGEL3.png",
    },
    {
        id:"compound-cutting-fluid",
        image:".images/MTL_SL_CCF.png",
    },
    {
        id:"crystalline-component",
        image:".images/MTL_SL_OC3.png",
    },
    {
        id:"grindstone",
        image:".images/MTL_SL_PG1.png",
    },
    {
        id:"incandescent-alloy",
        image:".images/MTL_SL_IAM3.png",
    },
    {
        id:"integrated-device",
        image:".images/MTL_SL_BOSS3.png",
    },
    {
        id:"loxic-kohl",
        image:".images/MTL_SL_ALCOHOL1.png",
    },
    {
        id:"manganese-ore",
        image:".images/MTL_SL_MANGANESE1.png",
    },
    {
        id:"orirock-cluster",
        image:".images/MTL_SL_G3.png",
    },
    {
        id:"oriron-cluster",
        image:".images/MTL_SL_IRON3.png",
    },
    {
        id:"polyester-pack",
        image:".images/MTL_SL_RUSH3.png",
    },
    {
        id:"rma70-12",
        image:".images/MTL_SL_RMA7012.png",
    },
    {
        id:"semi-synthetic-solvent",
        image:".images/MTL_SL_SS.png",
    },
    {
        id:"sugar-pack",
        image:".images/MTL_SL_STRG3.png",
    },
    {
        id:"transmuted-salt",
        image:".images/transmuted-salt.png",
    },
    {
        id:"crystalline-circuit",
        image:".images/MTL_SL_OC4.webp",
    },
    {
        id:"cutting-fluid-solution",
        image:".images/MTL_SL_PLCF.png",
    },
    {
        id:"grindstone-pentahydrate",
        image:".images/MTL_SL_PG2.webp",
    },
    {
        id:"incandescent-alloy-block",
        image:".images/MTL_SL_IAM4.png",
    },
    {
        id:"keton-colloid",
        image:".images/MTL_SL_KETONE4.png",
    },
    {
        id:"manganese-trihydrate",
        image:".images/MTL_SL_MANGANESE2.png",
    },
    {
        id:"optimized-device",
        image:".images/MTL_SL_BOSS4.png",
    },
    {
        id:"orirock-concentration",
        image:".images/MTL_SL_G4.png",
    },
    {
        id:"oriron-block",
        image:".images/MTL_SL_IRON4.webp",
    },
    {
        id:"polyester-lump",
        image:".images/MTL_SL_RUSH4.png",
    },
    {
        id:"polymerized-gel",
        image:".images/MTL_SL_PGEL4.webp",
    },
    {
        id:"refined-solvent",
        image:".images/MTL_SL_RS.png",
    },
    {
        id:"rma70-24",
        image:".images/MTL_SL_RMA7024.png",
    },
    {
        id:"sugar-lump",
        image:".images/MTL_SL_STRG4.png",
    },
    {
        id:"transmuted-salt-agglomerate",
        image:".images/transmuted-salt-agglomerate.png",
    },
    {
        id:"white-horse-kohl",
        image:".images/MTL_SL_ALCOHOL2.webp",
    },
    {
        id:"bipolar-nanoflake",
        image:".images/Bipolar_Nanoflake.webp",
    },
    {
        id:"crystalline-electronic-unit",
        image:".images/Crystalline_Electronic_Unit.webp",
    },
    {
        id:"d32-steel",
        image:".images/D32_Steel.webp",
    },
    {
        id:"nucleic-crystal-sinter",
        image:".images/nucleic-crystal-sinter.png",
    },
    {
        id:"polymerization-preparation",
        image:".images/Polymerization_Preparation.webp",
    },
];
